### ISSUE TITLE
assert size != 0 under Linux

### ISSUE THREAD

**Issue by ChristophHaag** [StrayLightning/aeolius#27] opened 2017-08-29 02:31 UTC
A release build is segfaulting in the radv driver, so I was first looking into debug builds.

First fix was this one: https://github.com/StrayLightning/wyvern/pull/1

Now this is asserting: https://github.com/StrayLightning/wyvern/blob/228510d7f2729bb32b1d6e913808dff70273c34d/src/graphics/renderervk.rs#L2017

```thread 'main' panicked at 'assertion failed: size != 0', /home/chris/oldhome/build/wyvern/src/graphics/renderervk.rs:2017
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
             at /build/rust/src/rustc-1.19.0-src/src/libstd/panicking.rs:511
   6: wyvern::graphics::renderervk::RendererVkBuffer::new
             at /home/chris/oldhome/build/wyvern/src/graphics/renderervk.rs:2017
   7: wyvern::graphics::renderervk::RendererVkUniformBuffer::new
             at /home/chris/oldhome/build/wyvern/src/graphics/renderervk.rs:1973
   8: wyvern::graphics::renderervk::RendererVk::setup
             at /home/chris/oldhome/build/wyvern/src/graphics/renderervk.rs:335
   9: <wyvern::graphics::renderervk::RendererVk as wyvern::graphics::renderer::Renderer>::finish_resource_initialisation
             at /home/chris/oldhome/build/wyvern/src/graphics/renderervk.rs:3519
  10: aeolius::main
             at src/bin/aeolius.rs:308
  11: __rust_maybe_catch_panic
  12: std::panicking::try
  13: std::panic::catch_unwind
  14: std::rt::lang_start
  15: main
  16: __libc_start_main
  17: _start
```

gdb in frame 8 says
```
(gdb) print *block_spec
$11 = wyvern::graphics::resources::UniformBlockSpec {size: 0, set: 0, binding: 4294967295, block_type: wyvern::graphics::resources::UniformType::UniformBuffer, uniforms: collections::vec::Vec<wyvern::graphics::resources::BlockUniformSpec> {buf: alloc::raw_vec::RawVec<wyvern::graphics::resources::BlockUniformSpec> {ptr: core::ptr::Unique<wyvern::graphics::resources::BlockUniformSpec> {pointer: core::nonzero::NonZero<*const wyvern::graphics::resources::BlockUniformSpec> (0x7ffff4b13a40), _marker: core::marker::PhantomData<wyvern::graphics::resources::BlockUniformSpec>}, cap: 1}, len: 1}}
(gdb) print *block_name
$13 = &str {data_ptr: 0x555555c11bd0 <str.4n> "wireframe_uniformswireframe\000", length: 18}
```
so yea, size is 0.

Not sure where it is supposed to be computed, so for now I'll just leave this here. May be a driver bug.

**Comment by StrayLightning** [comment] 2017-08-30 15:43
Thanks for the reports and the pull request.  I'll try and take a look into these, but I suspect due to commitments I won't be able to for a little while.

**Comment by StrayLightning** [comment] 2017-10-02 10:20
I can confirm that this is an application issue, and not a driver bug.  I have clearly not been doing enough testing on Linux recently.  There are a bunch of validation layer errors being thrown up by the latest SDK that I will look at as well.

**Comment by StrayLightning** [comment] 2017-10-02 18:21
Fixed by commit e4743a35bcf7c46bcb9fe52ddd69a4a9121e1227 that pulls in Wyvern 0.4.2.

**Closed by StrayLightning** 2017-10-02 18:21 UTC

**Comment by StrayLightning** [comment] 2017-10-02 18:23
I'm looking into sourcing a Radeon R9 or later to test more widely, but I'm hoping that with this change the application will now run under Linux/RADV.

**Comment by ChristophHaag** [comment] 2017-10-02 18:51
Cool. My PC is currently waiting for a Ryzen CPU replacement, but I'll try it then.
